### ISSUE TITLE
[Quest] Rolling with my Homies - ID 14071 - (issue 2) Blocks goblin start chain - Kezan

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#152]
https://www.wowhead.com/quest=14071/rolling-with-my-homies
I cant do quest without hot rod,
if is quest solved with solving issue of hot rod just label as invalid.

**Comment by realdude19** [comment]
12/21/2018 
Can't mount hotrod, Hotrod spawns and you are not put in the driver seat nor can you get in it.
The quest requires you to pick up three friends in your hotrod, that you can't get in yourself. 
The quest can not be done until the hotrod problem is fixed.

**Comment by Rushor** [comment]
Fixed with gossips, so you can talk to them and complete the quest.

**Comment by Dranah** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/854 seems the quest still doesnt work

**Comment by Jekenius** [comment]
There is another minor thing about hot rod riding: when you're hitting wandering npc with a hot rod, they should be knocked back and should say some phrases about player's driving skills(can be nicely seen here: https://youtu.be/iOqHwT1k35U?t=60)

**Comment by Echinaceax** [comment]
@Jekenius - can you add a new report (issue 3) please for this one. thank you

**Comment by Rushor** [comment]
made it more easy for new player. credit is now given on close to creatures

![I](https://i.imgur.com/RIYMq4X.jpg)
![I](https://i.imgur.com/1ZSrRqc.jpg)
![I](https://i.imgur.com/8go65yp.jpg)

**Comment by polymorphism98** [comment]
This is working fine, I just completed it. The only glitch is that Izzy, Gobber and Ace are also present very near to the quest giver, in addition to them being present at their original positions(Goober: 60,49 | zzy: 56 76 | Ace: 47,34). When you drive to these duplicate NPCs, you dont get the credit. This could be a little confusing. But otherwise, the quest works smooth.
