### ISSUE TITLE
Riding Trainers

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#2011]
**Links:**

Flight form : https://cata-twinhead.twinstar.cz/?spell=33943
Swift flight form : https://cata-twinhead.twinstar.cz/?spell=40120

Riding skills : 
- Apprentice : https://www.wowhead.com/spell=33388/apprentice-riding
- Journeyman : https://www.wowhead.com/spell=33391/journeyman-riding
- Expert : https://www.wowhead.com/spell=34090/expert-riding
- Artisan : https://www.wowhead.com/spell=34091/artisan-riding
- Master : https://www.wowhead.com/spell=90265/master-riding

**What is happening:**

I bought the riding skills until Expert Riding and after I bought the druid swift flight form, the only skill available to buy was the Apprentice.

**What should happen:**

The riding skill available should have been Artisan riding.

**Comment by Kitzunu** [comment]
You learn all riding skills up to Artisian when you get Flight Form.

>It is free, while regular training and a mount costs 250g.  [Swift Flight Form] is attained by learning it from a Druid trainer (20gg), though artisan riding skill (5000g) is still required.

**Comment by Chicozoba** [comment]
I have paid the Flight form and got the riding skill for free. But now I have to pay everything again
![Screen](https://user-images.githubusercontent.com/50930065/58295269-9b139e80-7dce-11e9-9a6e-7a651ac2b4ed.jpg)

The flight form spell you can see on the screenshot is the swift one.

**Comment by Kitzunu** [comment]
Fixed for all trainers

**Comment by Echinaceax** [comment]
> Fixed for all trainers

Can we confirm that the riding trainers are fixed for druid and none druid classes ?

**Comment by Kitzunu** [comment]
It is fixed. 

It will be pushed whenever Janitor feels like it is time to update Live

**Comment by Echinaceax** [comment]
> It will be pushed whenever Janitor feels like it is time to update Live

@Kitzunu - jani did it for me same day (sorry for late update)

**Comment by Echinaceax** [comment]
@wow-mania - not fixed, player relearnt from druid trainer but still get offered at the riding trainer 
see learnt and see ride trainer window
https://prnt.sc/nu3f4i

**Comment by TheSale** [comment]
I have experienced same issues as others, I had unlearned random skills and had to train again, and also my riding skills 
http://prntscr.com/nthsob
this was first time I had to re learn skills, and in chat I had displayed some riding skills that I had learned again...
at that moment I did not know what is going on, later echi explained to me that it was actually a bug.

now janitor told me that everything is okay and not I have for the third time to re learn everything
in chat you can see some of abilities that I have learned, and flying I started to learn with hope that it night be just first one that must be learned or second or third... but I stop learning when I had to waste 3 digit gold
http://prntscr.com/nu3f4i

**Comment by Chicozoba** [comment]
Hello, I leveled up another druid and had the same issue (After buying the flying form, the trainer still asks me to buy the Expert riding skill that's supposed to be learnt).
![Sans titre](https://user-images.githubusercontent.com/50930065/60287573-80bf6a00-9912-11e9-8c6b-61e03ed97bb5.png)

**Comment by Rushor** [comment]
Can you tell me where you can buy the spell https://cata-twinhead.twinstar.cz/?spell=33943 / https://cata-twinhead.twinstar.cz/?spell=40120 as mentioned in the start of the issue?

**Comment by Echinaceax** [comment]
@Rushor 
horde 
report https://github.com/WoWManiaUK/Blackwing-Lair/issues/1955
npc https://www.wowhead.com/npc=44726/shalla-whiteleaf

Ally 
npc https://www.wowhead.com/npc=44395/celestine-of-the-harvest

**Comment by Rushor** [comment]
Reason found!

You learned the wrong spell from those trainers.

Updated it. So you need to see you normal riding trainer in order to get the ability to buy flight forms. This way the spells will saved!

tested it and it works even after relog.

![I](https://i.imgur.com/1UkikWQ.jpg)
![I](https://i.imgur.com/dieT5Q7.jpg)
![I](https://i.imgur.com/61uPvJi.jpg)
![I](https://i.imgur.com/m6CUWys.jpg)

**Comment by Echinaceax** [comment]
nice work @Rushor 
thanks so much :)

**Comment by Rushor** [comment]
updated one more pls test

**Comment by Echinaceax** [comment]
Problem regressed again 

reported by ingame player to a GM

**Comment by mfranca0009** [comment]
[Flight Form] trains [Expert Riding] automatically, while [Swift Flight Form] requires you to purchase [Artisan Riding] first in order to train it. The [Artisan Riding] requirement was not being shown for the [Swift Flight Form] spell at the trainer, this has been corrected now.

Testing the original issue at hand, could not reproduce this problem as of today, and you still have your riding skills and druid shapeshift forms as it should be on re-logging in.
