### ISSUE TITLE
[Item]  Badge of justice

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2074]
**Links:**

https://cata-twinhead.twinstar.cz/?item=29434    link to the item

**What is happening:**

upon killing a member of the opposite faction one of these badges are getting placed into the players bags,  no video for this one sorry as i had already killed the alliance filth !

**What should happen:**

should just receive honor points which go in currency,  this actually happens and you do get the honor points,  but you also get a badge in your bags for some reason

**Comment by TheSale** [comment]
http://prntscr.com/nu41dq
confirmation

**Comment by sarahkay88** [comment]
this also happened on test realm after I killed @giles1508  I ported him to dalaran and killed him got 1 hours and 1 badge in my bags

**Comment by Bathelmo** [comment]
sounds like a regular config misconfiguration to me. @wow-mania

**Comment by Rushor** [comment]
tested with echi. fixed now.

**Comment by Echinaceax** [comment]
Not fixed - regressed 

![still dropping 2](https://user-images.githubusercontent.com/39439201/74895395-cba25c00-5391-11ea-9f52-4dae3e8fdd7a.jpg)

**Comment by mfranca0009** [comment]
Specifically related to the server configuration, PvP Token needs to be disabled until we implement a custom PvP token for the Reign server.

**Comment by Echinaceax** [comment]
@wow-mania ive assigned you to this :)
