### ISSUE TITLE
[Debuff] Firegut Fear Storm - ID 13488 - Burning Steppes

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2294]
**Links:**
Spell: https://www.wowhead.com/spell=13488/firegut-fear-storm

**What is happening:**
As soon as i enter Morgans Vigil Area in Burning Steppes the Debuff is applied to my character. This leads to a never ending fear bug. 
Only way to solve is, to relog and run away from the area.
![Firegut Fear Storm](https://user-images.githubusercontent.com/18005338/59094191-ee7d0500-8915-11e9-91ee-443d019d831c.png)

**What should happen:**
The debuff should not be applied to the player.

**Comment by Kitzunu** [comment]
I found the cause of it, this blue thing is somehow casting this. 
![image](https://user-images.githubusercontent.com/24550914/59105672-b2a56800-8934-11e9-9ed7-08888aa829e9.png)

It is spawned with GObject 160839 however if you remove the object that crystal does not disappear... as far as I know that crystal should not even be there, so I have no idea what it is or how it is spawned.

@Rushor You got any idea?

**Comment by Kitzunu** [comment]
I imported a script from tc...
I hope this will work

**Comment by Echinaceax** [comment]
@Kitzunu the cause was found here before from Angel and me https://github.com/WoWManiaUK/Blackwing-Lair/issues/1719

So it was fixed so what has this double fix done now then ?

**Comment by Kitzunu** [comment]
The object you reported did not cause the debuff, I did some searching in the DB and it was the blue weird thing that caused it.

I don't know if the script I added will fix it tho...

**Comment by zippoking** [comment]
For me it is not fixed. As soon as i enter the area (or maybe come close to the blue thing) i get the debuff.

**Comment by Echinaceax** [comment]
not fixed @Kitzunu still happening :)

will set to @Rushor now

**Comment by Priestelar** [comment]
still a problem!
![WoWScrnShot_102219_210616](https://user-images.githubusercontent.com/16594771/67321600-fed1fd00-f50f-11e9-92b9-f6ac034103b8.jpg)

**Comment by Rushor** [comment]
okay now fixed. removed the spell form the object :)

**Comment by Priestelar** [comment]
tnx so much @Rushor! :D
