### ISSUE TITLE
[Guild]   Guild dethrone

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2480]
**Links:**

https://wowwiki.fandom.com/wiki/Guild_Dethrone

**What is happening:**

in 4.3 there was an automatic guild dethrone added which enabled the next ranking guild member that has logged in on the most recent week to be able to take control if the guild leader is awol for 30 days or more and this isnt currently working,  there is no notification showing in the guild news and events for the next highest ranking player in guild

**What should happen:**

there should be a notification in the guild news and events window which allowas the next ranking guild member to be able to click on it and then it brings up a confirmation box to make sure the player knows he is taking over as the new guild master

**Comment by giles1508** [comment]
spoke with metaxa today who is going to manually demote and promote within the guild today,  but he wanted me to make a post to get this fixed with the devs

**Comment by Kitzunu** [comment]
https://wowwiki.fandom.com/wiki/Guild_Dethrone

I can confirm that this feature does not work. However it is not 30 days, it was hotfixed to 90 days as per my source above so that works as intended.

The "announcement" does show, however when you press "dethrone" nothing happens.

![image](https://user-images.githubusercontent.com/24550914/67425412-373d0e00-f5d8-11e9-8abf-9d6db8b5c1cb.png)
![image](https://user-images.githubusercontent.com/24550914/67425431-40c67600-f5d8-11e9-9677-3a40573d985c.png)

How it is supposed to work:
When you press "Dethrone" the old guildmaster should be removed from the post and the new one be assigned.

**Comment by Rushor** [comment]
needs merge of https://github.com/TrinityCore/TrinityCore/commit/6b9948857057cfe495807a61b6797c75d9fc7a6a

**Comment by Keader** [comment]
@Rushor Not possible just port.
Missing all Packet Handle Rewrite to port this lol

**Comment by Rushor** [comment]
:( oh

**Comment by Rushor** [comment]
i will try an other script

**Comment by Rushor** [comment]
we are not on that patch currently - weill be fixed once we progressed.

**Comment by Kitzunu** [comment]
fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/4096
> Fix feature that allow players take guild, when guild leader is offline for long time.

**Comment by Echinaceax** [comment]
Seems Dethrone is still not working 
GMs has had a ticket saying its not working still

**Comment by Echinaceax** [comment]
update info on this one @mfranca0009 

It was disgussed tha it would be 30 days (in 2020) due to low pop
can do 90 days when pop grows
