### ISSUE TITLE
[Spell] Frostfire Bolt - Spell ID 44614

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2656]
Links:

https://wotlk.evowow.com/?spell=44614

What is happening:

Frostfire Bolt is doing less damage then announced on Tooltip
Tooltip says **7985** Damage (for 5437 Spellpower)
Damage on dummy without any buff : See following screenshot
https://puu.sh/DPn8I/c9acb29062.png

What should happen:

Dr.Damage for Frostfire Bolt says that Coeff is about 97.7% of Spellpower
(Proof : https://puu.sh/DPn8N/1598b49087.png )

**PLUS** 

The glyph is present on the default version of the spell (with no glyph), meaning we do have the DoT even without the glyph, which isn't supposed to be here.

**Comment by Rushor** [comment]
bonus added, fixed with next server update

**Comment by Dranah** [comment]
Instant damage now matches.
The DoT damage is still present without glyph.

**Comment by Keader** [comment]
Hmm, glyph stuff is fixed here: #2656
