### ISSUE TITLE
[Quest] The Lost Brother - ID 28233 - Twilight Highlands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2674]
**Links:**
Quest: https://www.wowhead.com/quest=28233/the-lost-brother
NPC which is missing: https://www.wowhead.com/npc=48053/bahrum-forgehammer

**What is happening:**
The npc is missing on the box where he should be.
![The lost brother - how it is](https://user-images.githubusercontent.com/18005338/60767301-793c5580-a0b6-11e9-8558-e0ad24b6585c.png)

**What should happen:**
The npc Bahrum Forgehammer should be on the box.
![Picture](https://wow.zamimg.com/uploads/screenshots/normal/203823-bahrum-forgehammer.jpg)

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/4ioNA83.jpg)

**Comment by nudelchris** [comment]
![WoWScrnShot_071119_005025](https://user-images.githubusercontent.com/52678929/61010321-12e55a80-a376-11e9-8d6f-a12b407e7226.jpg)


still not there
