### ISSUE TITLE
[Quest] Terokk's Downfall

### ISSUE THREAD

**Issue by Wildtusk** [WoWManiaUK/Blackwing-Lair#2760]
**Links:**
https://www.wowhead.com/quest=11073/terokks-downfall
https://www.wowhead.com/npc=21838/terokk
from WoWHead or our Armory

**What is happening:**
After Terokk is summoned via the Ancient Skull Pile, trying to engage him gives the error 'you cannot attack that target'. He cannot be engaged, and does not attack or interact even when other local npcs are fought near him. This is true both under the effects of the Elixir of Shadows and when not under its effects, as he was summoned with the elixir effect on, and then with the buff removed.

**What should happen:**
He should behave like a normal elite enemy and be able to be fought, damaged, and eventually killed.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/W3E9YGj.jpg)

**Comment by Notwindy** [comment]
quest is not fixed, you can fight Terokk but after he becomes immune you cant break it or do anything to kill him.

At 20% Terokk becomes Immune to all attacks, and you'll see a blue flare shortly afterward, where a bomb will drop down. Drag Terokk into the flame to break his shield. He'll become enraged but you'll be able to kill him.

Bomb never drops.

If you fix this i thank you very much <3

**Comment by Echinaceax** [comment]
https://www.wowhead.com/quest=11073/terokks-downfall#comments

correct info by https://github.com/WoWManiaUK/Blackwing-Lair/issues/2760#issuecomment-551910607

**Comment by Shakespells** [comment]
In game, the bomb is still not dropped.

**Comment by golosomie** [comment]
pending for .bq command

**Comment by mfranca0009** [comment]
Starting from scratch on this one

**Comment by mfranca0009** [comment]
Fixed but needs a bit of testing for various conditions tomorrow @Echinaceax

**Comment by Echinaceax** [comment]
> Fixed but needs a bit of testing for various conditions tomorrow @Echinaceax

Sure, no problem @mfranca0009

**Comment by mfranca0009** [comment]
Ancient Skull Pile gameobject is entirely messed up, upon despawn it never respawns based on its initial respawn time and forcing it to respawn using SAI SMART_ACTION_FORCE_DESPAWN with a respawn time doesn't respawn the object either.

Looking into this later.

**Comment by mfranca0009** [comment]
All set 👍
