### ISSUE TITLE
[NPC] Seer Kormo - ID 43397 - missing quests - Deepholm

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2807]
**Links:**
NPC: https://www.wowhead.com/npc=43397/seer-kormo
Quest 1: https://www.wowhead.com/quest=27136/elemental-energy
Quest 2:  https://www.wowhead.com/quest=26244/the-earth-claims-all

**What is happening:**
At the moment Seer Kormo does not offer any quest at all. He should offer the two mentioned quests. According to the  wowhead comments, the only requirement is the the quest [Deepholm, Realm of Earth](https://www.wowhead.com/quest=27123/deepholm-realm-of-earth)

![Seer Kormo - how it is](https://user-images.githubusercontent.com/18005338/61579983-e0bdc080-ab0c-11e9-9477-73138f403e4e.png)

**What should happen:**
He should offer the two mentioned quests.
![Seer Kormo - how it should be](https://user-images.githubusercontent.com/18005338/61579982-e0252a00-ab0c-11e9-9b6c-4e18a65f1625.png)
![Seer Kormo - how it should be 2](https://user-images.githubusercontent.com/18005338/61579984-e0bdc080-ab0c-11e9-86f0-4119ac838058.png)

**Comment by wow-mania** [comment]
Fixed.
Make sure you have pre-req quests
![image](https://user-images.githubusercontent.com/12248683/61588656-6ab26b80-ab97-11e9-92d9-54ae383c570b.png)

**Comment by zippoking** [comment]
He still does not offer quests for me. I tried it with a new char and did the pre-quests to get into Deepholm. But as you can see on the Screenshot, he offers no quests. I only have the one quest from the guy next to him in my questlog.

Is the quest [Deepholm, Realm of Earth](https://www.wowhead.com/quest=27123/deepholm-realm-of-earth) really the only requirement needed?

![Seer Kormo - how it is 2](https://user-images.githubusercontent.com/18005338/61627062-29958680-ac7f-11e9-8823-f27c3f8fd105.png)

**Comment by Rushor** [comment]
@zippoking you need http://cata.cavernoftime.com/quest=26245 first completed

changed to https://www.wowhead.com/quest=27123/deepholm-realm-of-earth requiremdn only with next update
