### ISSUE TITLE
[DUNGEON] Dire Maul West: Doors are cant be opened. (issue2)

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3121]
**Links:**

from Wowhead or our Armory
![image](https://user-images.githubusercontent.com/26048748/63327735-741a2980-c337-11e9-9d1e-f33578f6e55d.png)

**What is happening:**

On the screenshot, Player coordinates (Courtyard door) cant be opened.
On the screenshot, Cursor coordinates (inner door) can't be opened. (i did not see the door in the live server but it is probably bugged too)

**What should happen:**

Player Coords -> Courtyard Door should able to open.
Cursor Coords -> Inner Door should able to open.

**Comment by kDracku** [comment]
#1887

**Comment by Eirolla** [comment]
not same with #1887 its Dire Maul West.

**Comment by Eirolla** [comment]
https://www.wowhead.com/item=18268/gordok-inner-door-key#comments:id=1206405 doors do not need the key to open.

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63347270-6e383e80-c35f-11e9-9e92-18913cad8939.png)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63347333-29100e80-c357-11e9-9e99-cbb85ff04e84.png)

fixed, no key req

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63387473-2391e300-c3ae-11e9-89fe-ac20d93c2936.png)
not fixed this one

**Comment by Kitzunu** [comment]
Delete cache

**Comment by Kitzunu** [comment]
Tested it myself and it works

**Comment by Nirvanum** [comment]
Cache deleted -> Don't work
Reset instance -> Don't work
Kill everybody -> Don't work
Crescent Key -> Don't work
Volatile Seaforium Blastpack -> Don't work
Knock Knock -> Don't work

Some advice?

**Comment by Nirvanum** [comment]
![immagine](https://user-images.githubusercontent.com/52670055/67146502-f6699000-f28b-11e9-80b3-c1ac52ba4b01.png)
This is the Locked Door in Dire maul West

**Comment by Jimpaa** [comment]
The door is still locked and cant enter it. I have cleared the beacons like you are suppose to @Rushor

**Comment by Kitzunu** [comment]
If a door is supposed to be unlocked and it is not in Dire Maul West, open a new report

**Comment by Jimpaa** [comment]
Its the same door as the photo above the instance is called Capital Gardens didnt know it was west :) @Kitzunu
