### ISSUE TITLE
[General] characer stuck on flightpath mount 

### ISSUE THREAD

**Issue by picekolo** [WoWManiaUK/Blackwing-Lair#3216]
**Links:**

from WoWHead or our Armory

**What is happening:**

Am stuch on flyng mount and cant dismount it,cant die,and when i relog in game it automaticli starts flyng to location and teleports me back to starting point but mounted on fly mount. 

**What should happen:**

**Comment by Echinaceax** [comment]
need more info @picekolo 
where did you first get on the the mount, is it a flight path ?
what zone was it ?
where was you trying to flight to?
is it a quest ?

**Comment by picekolo** [comment]
Its fly path from Lights hope  chapel in Eastern Plaguelands to Fuselight,Badlands. It teleports me to inn in Light hope chapel when i come near Twilight Highlands. and when teleported back in inn i got stuck on mount and cant dismount it and hostile npc dont attack me.

**Comment by Echinaceax** [comment]
thanks @picekolo 
yes thats the fath i tested a few days ago for somone else and i couldnt reproduce this bug (tested in DEV server) i will log soon on live and see if i can reproduce this bug on there and update here soon

**Comment by Echinaceax** [comment]
has to be a launcher issue

**Comment by Kitzunu** [comment]
Try again, but with a char under 55

**Comment by Echinaceax** [comment]
> Try again, but with a char under 55

will retest tomorrow @Kitzunu

**Comment by picekolo** [comment]
morning character is Horde-orc lv44 and still stuck. Luncher is up to date

**Comment by picekolo** [comment]
i use undead fly master - left one

**Comment by Echinaceax** [comment]
i will test after dinner , and update here soon

**Comment by picekolo** [comment]
![WoWScrnShot_090619_114804](https://user-images.githubusercontent.com/54933044/64419220-ac8e6700-d09c-11e9-8e73-85641eed94c8.jpg)

**Comment by picekolo** [comment]
am mounted and can walk around,but cant enter dungens,get attackt or talk to other npc,and when i try to drown character i cant die,and when i restart game it automatically goes in loop to fly to badlands and tp me back to inn on mount.

**Comment by Echinaceax** [comment]
@Rushor - UPDATE

i did my reset from a lvl 44 char, and can confirm that players using the flight path from **Eastern Plaguelands** to **Fuselight**,Badlands Indeed gives you a loading screen and redirects the player away from the destination chosen (Fuselight) 

![TEST COMPLETE](https://user-images.githubusercontent.com/39439201/64419597-861cfb80-d09d-11e9-944b-128e2881d78f.jpg)

**Comment by Rushor** [comment]
this more sth like for keader

**Comment by zanadu** [comment]
Has there been a fix to this I am level 46 and currently stuck in this loop from Eastern Plague lands to Fuselight. Flight path goes through the ground then turns around. After a short time I am teleported to Stormwind on the flying mount but only move at walking speed. Cannot dismount, cast, or enter any dungeons.

**Comment by Echinaceax** [comment]
@zanadu - for now ask a GM in a ticket to help you , just make a ticket ingame and they will help you

**Comment by Keader** [comment]
I cant reproduce in my core.
even with low level character.

**Comment by Echinaceax** [comment]
> I cant reproduce in my core.
> even with low level character.

very odd, but understood what we spoke about via discord @Keader

**Comment by Keader** [comment]
Fixed folks.

**Comment by Echinaceax** [comment]
@Keader not fixed, GMs are still getting tickets about this issue

**Comment by Keader** [comment]
Something reverted, because was working
I Will look again today

**Comment by Keader** [comment]
Fixed the root cause.
Should not happens again.
You can test in ptr.

**Comment by Echinaceax** [comment]
> You can test in ptr.

**Test1**
- [ ] flight from Lights hope chapel (EP) to fuselight (Badlands) (completed)

**Test 2**
- [ ] flight from fuslight (Badlands) too eastwall tower (EP) (completed)

Seems fine again now @Keader 
flies beautifully through Twilight Highlands :)

Thanks
