### ISSUE TITLE
[Dungeon Finder] Everything related to dungeonfinder

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#4011]
- 1. Heroic lockouts + RaidLockout 
- 2. "dungeon Finder" timer bug, no remove wrong que
- 3. Teleportoption for "Dungeon Finder" que
- 4. Dungeon queue system

1. 

**Links:**

http://us.battle.net/wow/en/game/patch-notes/4-3-0#dungeons   
this is a link that will take you to a changelog for 4.3 and its set on the duneon finder part,   dont scroll,  read from here

**What is happening:**

ok basically at the moment,  players can only do each  heroic once per day, and then they can no longer queue for random heroics without getting the same shadowfang keep heroic over and over

**What should happen:**

in 4.3 blizzard changed it so you dont ever get locked to a heroic instance if you queue via the random finder,  you only get locked if you enter manually,   or queue specific

and even then , even if you was locked to a specific instance you could still get any random heroic all day every day by queuing for it on the random finder,   at the moment this is causing ques for heroics to become massive because peopel do not want to do shadowfang keep over and over,   they want to be able to get different ones like it should be.

this makes matters worse with the current new low population, as very limited people are doing heroics as it is,  without only doing 6 a day then stopping

we need to remove the lock for random finder for heroic and make it so you only get locked when you want to queue specifically for 1 instance,  and again even after queue do a heroic specifically you should still be able to queue for randoms all day and randomly get any available heroic that we have open

2. 
**What is happening:**

https://imgur.com/a/wKs2EsU 
The photo above is taking after being offline doing some other stuff so i wasnt even online during these 3 hours. 

I woke up the day after and it looks like this. So the timer keeps going even tho i wasnt even in que before logging out 
https://imgur.com/a/z8PT99Y

I have been unaura by GM i even deleted my cashe.

**What should happen:**

3. 
**What is happening:**

When i use a portal or just travling around the world and get a cutscene it kicks me from the dungeonfinder. If im in grp with someone and that person que us up the eye will vanish but we will still be in que.

**What should happen:**
The eye should not vanish or kick you out of dungeon finder when you use a portal or get a cutscene out in the world.

4.
**Links:**

from WoWHead or our Armory

**What is happening:**

So, the queue system atm is broken. For a few days now I and a lot of people get this problem. When I'm in queue as for example dps and in the queue there are heal,tank and 1 more dps with me, so we are waiting for 3rd dps, I suddenly go to solo queue... alone. This has happened like 10 times now and it's getting really annoying because other people get the same problem too and we can't queue for a dungeon. Once I went alone in a new queue (When I haven't even left the que before that and was waiting just for 1 dps to queue), I asked in world chat if people got the same solo que problem too. The answer was "Yes". 

**What should happen:**

Queue system should work normally and it shouldn't kick us in separate queues. I know it has something to do with which dungeon you are saved from, but the queue was almost full, so all the people that were in it should be able to do dungeons that I'm able to do too and not be kicked in separate queues.

**Comment by Jimpaa** [comment]
I qued in grp and it worked fine then when im trying to solo que it shows this https://imgur.com/a/Ngz3rMv

**Comment by Rushor** [comment]
on wotlk there was a fix for that i guess - most can be ported to my mind

**Comment by Echinaceax** [comment]
@Rushor this bugged timer for jimpaa also is only one of his chars not all of them, which makes this even more strange (DK) char if that matters

**Comment by Jimpaa** [comment]
Not even solo que removes the timer. Just tested it.

**Comment by Echinaceax** [comment]
**"Dungeon Finder" The Eye for que**
@Rushor 
Also seen that the potion of Deepholm has the eye removed from que (visual bug) 
https://www.wowhead.com/item=58487/potion-of-deepholm

**Comment by questbugreporter** [comment]
If someone is in queue and in a party with someone else, logging out doesn't remove them from the queue.

**Comment by Echinaceax** [comment]
> Not even solo que removes the timer. Just tested it.

i have same bug on RDF que 

![18h bug](https://user-images.githubusercontent.com/39439201/70376844-b0d15700-190d-11ea-8a16-331523635179.jpg)

**Comment by Echinaceax** [comment]
### [Dungeon Finder] Leave group bug (client crash) #4065

- [ ] 5

**Comment by Lumber-Jack-2** [comment]
In the scenario when a player leaves/dcs from your dungeon group and is either vote kicked from the party or leaves the party then there are 2 options to readd a player to the dungeon.

There are 2 issues with the 2 available options

- [ ]  6 - Reque with the dungeon finder option - I feel like this doesn't work correctly, When we lost 1 dps today and requed into the dungeon, not sure if the search option actually accepts players already in the dungeon que. I asked players in my guild to join rhc que when one dps dcd but no one was able to join our dungeon despite several of them whom were eligible for the dungeon did not get into the dungeon.

- [ ]  7 - Invite a player to the party - When you do manually invite a player to your party, the whole group will then not get valor on the last boss. This should only happen to the player who gets the group invite since they didnt get the "random" heroic dungeon bonus. But at the moment the whole dungeon group loses their end of dungeon valor and maniac point rewards :(

**Comment by Echinaceax** [comment]
- [x] ### 8 - Players not getting their Daily RDF rewards of 140JP and MP /150VP and MP)

https://github.com/WoWManiaUK/Blackwing-Lair/issues/2450#issuecomment-572606916

#4508 fixed in dev

**Comment by TheSale** [comment]
> * [x]  ### 8 - Players not getting their Daily RDF rewards of 140JP and MP /150VP and MP)
> 
> [#2450 (comment)](https://github.com/WoWManiaUK/Blackwing-Lair/issues/2450#issuecomment-572606916)
> 
> #4508 fixed in dev

not fixed, there is still issue where players dont recieve justice points
