### ISSUE TITLE
[NPC] Argent Squire/Argent Gruntling

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4199]
### Reported by ingame player Nub

**Links:**
### Rewarded from 
http://cata.cavernoftime.com/?search=A+Champion+Rises

Argent Squire - https://cata-twinhead.twinstar.cz/?npc=33238
Argent Squire - Cant find info on http://cata.cavernoftime.com/npc=33238

**What is happening:**
- the NPC is meant to be a vendor
- At the moment he isnt a vendor

**What should happen:**
- Should be a vendor and sell stuff and other functions etc..
https://wowwiki.fandom.com/wiki/Argent_Squire

![npc](https://user-images.githubusercontent.com/39439201/74089733-7bc7b900-4aa4-11ea-8287-cb9444236ad4.jpg)

thank you for reporting it to me Nub :)

Note need to check the Horde Argent Gruntling too
http://cata.cavernoftime.com/item=45022

**Comment by Echinaceax** [comment]
Tested Horde on DEV 
its fine, so only Ally broken 

![horde is fine](https://user-images.githubusercontent.com/39439201/74090064-da426680-4aa7-11ea-9f7e-d94867e02bd7.jpg)

**Comment by Rushor** [comment]
i remember some achievement condition for that

**Comment by Echinaceax** [comment]
player hasnt completed the horde quest is that what you mean ?

**Comment by Rushor** [comment]
alright fixed :)

**Comment by Rushor** [comment]
https://i.imgur.com/7e2hX7J.jpg

**Comment by Echinaceax** [comment]
### Updated info

recent Mania report states that there is a upgrade process for the vendor option 


mania report https://github.com/WoWManiaUK/Redemption/issues/4951

**need same fix here with same conditions** as rushor says here https://github.com/WoWManiaUK/Redemption/issues/4951#issuecomment-688510881

Horde http://cata.cavernoftime.com/item=45022
Ally http://cata.cavernoftime.com/item=44998

https://www.wowhead.com/item=47541/argent-pony-bridle#comments
**_"After finding out that my Argent Squire could be a 4hr CD on demand mobile bank/mailbox, I was super excited to get him. Frankly, I'm surprised that not more people talk about this pet. Spent a month or so farming the dailies required to purchase this item and... the mobile bank/vendor/mailbox feature that this item allows you to use is only available for the toon that earned and used this item. _**


### Tested PTR

- [x] ATM we have all without upgrade requirement
- [x] pet has no specific conditions set at all
- [x] Also the Argent Squire/Argent Gruntling doesnt have timer to use options within 3mins
- [x] Doesnt despawn after 3mins (to go shopping)
- [x] Resets the options after 3m after timer buff disapears, without despawn of 4hours

while having no upgraded version from https://www.wowhead.com/item=47541/argent-pony-bridle#comments

![no upgrade](https://user-images.githubusercontent.com/39439201/92516047-e3014380-f214-11ea-9f21-96ace8c6371e.jpg)

![5min spawn time](https://user-images.githubusercontent.com/39439201/92517779-8c493900-f217-11ea-98e6-c710fd1d4946.jpg)

remains spawned continuously (hes been spawned 1 hour now )

![remains spawned continuously](https://user-images.githubusercontent.com/39439201/92520273-a1c06200-f21b-11ea-8fb0-9d9e237de847.jpg)


### UPDATE FROM LIVE

same on live 

npc gets a buff of 3 mins after you chose an option but no despawn

![grunting shop buff timer](https://user-images.githubusercontent.com/39439201/92925228-7798bb00-f43a-11ea-9669-148276e0d56c.jpg)

when buff goes away all options reset = making this vendor have a constant up time

![after buff timer goes away all venter options are back](https://user-images.githubusercontent.com/39439201/92925307-9ac36a80-f43a-11ea-8d7a-2b47368c7bd3.jpg)

can still summon him after logout and chose options still even when he has the tired buff 

![tired buff](https://user-images.githubusercontent.com/39439201/92931867-681e6f80-f444-11ea-98dd-80e88565d4fe.jpg)

**Comment by mfranca0009** [comment]
Added conditions from a WoW-Mania SQL fix from Rushor, needs testing in PTR 👍 
https://www.youtube.com/watch?v=GFwa8XiZsP0

**Comment by mfranca0009** [comment]
**UPDATE**

Revised the C++ script and made some changes to the conditions, it should now work blizzlike referenced from the video above ^

Needs testing for both Horde and Alliance on PTR 👍

**Comment by Echinaceax** [comment]
@mfranca0009 almost all :)

- [x] ATM we have all options still without upgrade requirement (not fixed)
- [x] pet has no specific conditions set at all
- [x] Also the Argent Squire/Argent Gruntling doesnt have timer to use options within 3mins
- [x] Doesnt despawn after 3mins (to go shopping)
- [x] Resets the options after 3m after timer buff disapears, without debuff of 4hours

- [x] timer debuff (tired) working 
- [x] gone shop,bank, postmaster buff working

- [x] 1 option only working

**note:** Argent Squire/Argent Gruntling should not have any "vendor,mail,bank" options  until after upgrading to [Pony up ](https://www.wowhead.com/achievement=3736/pony-up)

**Comment by mfranca0009** [comment]
Moved all gossip menu option conditions to C++ script instead of using DB, should all work now properly. Needs testing 👍

**Comment by Echinaceax** [comment]
tested and all working in PTR 👍

**Comment by Echinaceax** [comment]
Live is also fixed 
If you havent got the upgrade = these are only pets, they become venders once you meet the requirements :)
