### ISSUE TITLE
[Quest] Parts is-Parts - southern barrens

### ISSUE THREAD

**Issue by BurningXz** [WoWManiaUK/Blackwing-Lair#4375]
https://www.youtube.com/watch?v=Ll_ywVkDKlk

https://www.wowhead.com/quest=24619/parts-is-parts

**What is happening:** after i use the quest item (Calder's Bonesaw) no parts of the corpse appear

**What should happen:** to use Calder's Bonesaw to make parts of the corpse and collect them

**Comment by Echinaceax** [comment]
Confirmed
Quest item is usable but no parts are given 
![quest item](https://user-images.githubusercontent.com/39439201/79455201-c9a0f600-7fec-11ea-98a0-76685a345f19.jpg)

https://www.youtube.com/watch?v=Ll_ywVkDKlk

**Comment by Keader** [comment]
fixed

**Comment by Echinaceax** [comment]
nope not fixed :)
https://www.youtube.com/watch?v=Ll_ywVkDKlk

**Comment by Keader** [comment]
janitor cleanup DB zzzz
try again now.

**Comment by Keader** [comment]
wait... try later.
i need wait janitor back zz
