### ISSUE TITLE
[RDF Daily ] No daily RDF rewards given for nm/hc dungeon finder

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4508]
**Whats happening**

GM just reported to me that they are getting tickets about the JP/VP issue for finishing the RDF 
they are not recieving the 140/150 at the finish of their RDF 

meant to get 140/150 (seems to not be working correctly) or the Maniac points. 

![randon jp not giving at the end](https://user-images.githubusercontent.com/39439201/68445412-2ac0d400-01da-11ea-921a-858336efe76a.jpg)

![VP](https://user-images.githubusercontent.com/39439201/82132084-3e2da700-97dc-11ea-96e2-636d81949eaf.jpg)

**Comment by Keader** [comment]
is fixed in ptr8

**Comment by Echinaceax** [comment]
Brilliant thanks @Keader

**Comment by Echinaceax** [comment]
not fixed @Keader 

just did the RHC , havent checked the RDF one yet

**Comment by Keader** [comment]
Looks like packet handler is not working .-.
I did a hackfix to allow it work.
Will not show in interface, but players will get rewards

**Comment by Echinaceax** [comment]
@Keader Not fixed still :)

1. Maniac points (fixed)
2. 150 Valor points added to currency tab (fixed)
3. After daily rhc/ rdf the screen is still active will update when all 7/7 have been done

**Comment by Echinaceax** [comment]
fixed for both justice points and valor points thx @keader :)
