### ISSUE TITLE
[Quest] Warchief's Command: Northern Stranglethorn!

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4824]
**Links:**

https://www.wowhead.com/quest=28688/warchiefs-command-northern-stranglethorn

**What is happening:**
- quest missing from the board in Undercity and Silvermoon

**What should happen:**
quest should be at the Warchief's Command board

**Comment by mfranca0009** [comment]
Fixed in PTR, needs testing 👍 @Echinaceax

**Comment by Echinaceax** [comment]
not fixed @mfranca0009 sorry

undercity still missing https://www.wowhead.com/object=207324/warchiefs-command-board
Silvermoon still missing https://www.wowhead.com/quest=28688/warchiefs-command-northern-stranglethorn

**Comment by Echinaceax** [comment]
will re test when PTR is up 👍
