### ISSUE TITLE
[Quest] Peculiar Delicacies - ID 24691 - Un'Goro Crater

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#514]
Quest - https://www.wowhead.com/quest=24691/peculiar-delicacies
Item drop - https://www.wowhead.com/item=50371/silithid-leg
npc - https://www.wowhead.com/npc=10977/quixxil

**_Obtain 96 Silithid Legs_**

- None are dropping 
- Ive checked drop rate, and they should be dropping 57- 70%
- Cant complete

**Comment by Kitzunu** [comment]
fixed will send later

**Comment by Myivo** [comment]
https://www.wowhead.com/npc=6551/gorishi-wasp should drop 6 of https://www.wowhead.com/item=50371/silithid-leg , not 1

**Comment by Icyytouch** [comment]
its dropping 1 leg per add though, so its still not fixed, This quest takes an hour to complete if done normally.. drop rate is way to low for this quest for it to collect 96 legs meaning 96 kills on adds

**Comment by Kitzunu** [comment]
Fixed
