### ISSUE TITLE
[Talent] Seals of Command - ID 85126

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#630]
1) The talent is not giving Seal of Righteousness the functionality of doing AoE attacks.

2) The talent is not giving a 7% weapon damage amplification/extra damage to any of the Seals.

"Your Seal of Righteousness, Seal of Truth, and Seal of Justice now also deal 7% weapon damage when triggered. In addition, your Seal of Righteousness now hits all enemy targets within melee range."

**Comment by Kitzunu** [comment]
No change

**Comment by Dranah** [comment]
SoR now properly cleaves all nearby targets.
However the 7% extra weapon damage is not added anywhere.

**Comment by Keader** [comment]
Shit, i fixed it and override my fix ._.
Anyway, fixed one more time.

**Comment by Dranah** [comment]
The 7% extra now properly procs off seals of justice and seal of truth.
Still does not add to Seal of Righteousness.

**Comment by Keader** [comment]
Seal of Righteousness is proccing?

**Comment by Dranah** [comment]
Should, but does not.

**Comment by Dranah** [comment]
Good now.
