### ISSUE TITLE
[quest=27845] [Marking the Fallen] - Swamp of Sorrows

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#756]
you can't mark the fallen soldiers with the flag as you suppose to,

i only end up with dragging the flag on my own back instead.

[quest=27845]
https://www.wowhead.com/quest=27845/marking-the-fallen

**Comment by zippoking** [comment]
Confirmed.

NPC: https://www.wowhead.com/npc=46881/fallen-marshtide-footman
Item: https://www.wowhead.com/item=62517/banner-of-the-fallen
Credit: https://www.wowhead.com/npc=46909/marking-the-fallen-kill-credit-alliance

So there are 2 bugs:
1. there are not fallen footman in this area.
2. The flag sticks to you back, if you use the item.

How it is:
![Marking the fallen - how it is](https://user-images.githubusercontent.com/18005338/59124261-8a7f2e80-895f-11e9-9f90-3f65eef05cb4.png)


How it should be:
![Marking the fallen - how it should be](https://user-images.githubusercontent.com/18005338/59124265-8bb05b80-895f-11e9-87be-0429266467b0.png)

**Comment by Echinaceax** [comment]
**Update on** 

> 1. there are not fallen footman in this area.

there are but the issue is that both (Ally) fallen footmen and (horde) stonard warriors are fighting at the same pace, you have to wait to see who drops first :)

![same pace](https://user-images.githubusercontent.com/39439201/88626144-66723580-d0aa-11ea-96e0-da6021737eb3.jpg)

But there are a few standing idle

**Comment by mfranca0009** [comment]
Should be fixed, proper NPCs spawned and are "dead", on spell cast gives 1 quest credit and flag appears on body.

**Comment by Echinaceax** [comment]
fixed in PTR confirmed 

spawns are better 

![ally fix](https://user-images.githubusercontent.com/39439201/88724883-83028200-d12b-11ea-93ad-2f8edc784e19.jpg)

**Comment by rzenne** [comment]
the problem still seems to be happening. So there are 2 bugs:

    there are not fallen footman in this area.
    The flag sticks to you back, if you use the item.
