### ISSUE TITLE
[Quest] The Arts of a Shaman

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Blackwing-Lair#8]
**- How it should work:**
You need to learn Primal Strike and use it on Tiki Targets to complete this quest.

**- How it currently works:**
Using the spell on the Targets does not count towards the quest, so it is not completable. (the quest is necessary to advance in the troll starting quest chain)

**Comment by Zunrin** [comment]
The equivalent quests for other troll classes are bugged too.

**Comment by fvicaria** [comment]
This should be fixed tomorrow

**Comment by Zunrin** [comment]
This still does not work (tested with a shaman and a warlock)

**Comment by fvicaria** [comment]
Please add links to quest and spells.

**Comment by Zunrin** [comment]
- Shaman:
http://www.wowhead.com/quest=24760/the-arts-of-a-shaman
http://www.wowhead.com/spell=73899/primal-strike

- Warlock:
http://www.wowhead.com/quest=26274/the-arts-of-a-warlock
http://www.wowhead.com/spell=348/immolate

- Hunter:
http://www.wowhead.com/quest=24778/the-arts-of-a-hunter
http://wowhead.com/spell=56641/steady-shot

- Warrior:
http://www.wowhead.com/quest=26204/the-arts-of-a-warrior
http://www.wowhead.com/spell=100/charge

- Rogue:
http://www.wowhead.com/quest=24772/the-arts-of-a-rogue
http://www.wowhead.com/spell=2098/run-through (called eviscerate in cata)

-Priest: **(this quest is different, you need to heal NPCs but it does not work either)**
http://www.wowhead.com/quest=24784/learnin-tha-word
http://www.wowhead.com/spell=2061/flash-heal

- Mage:
http://www.wowhead.com/quest=24752/the-arts-of-a-mage
http://www.wowhead.com/spell=5143/arcane-missiles

- Druid: **(this quest is different, you need to heal NPCs but it does not work either)**
http://www.wowhead.com/quest=24766/the-arts-of-a-druid
http://www.wowhead.com/spell=774/rejuvenation


Note: the conditions and names of quests may have changed since cata so the wowhead info is out of date (the quest ids and spell ids are correct though).

**Comment by Zunrin** [comment]
The quests involving the Tiki Targets work.

The ones where you need to heal the Wounded Darkspear Watchers (priest and druid quests) are still an issue.

Also, the Tiki Targets are now unkillable (they will stay at one hp when trying to kill them) making the second troll quest impossible since it requires the player to destroy 6 Tiki Targets.

**Comment by fvicaria** [comment]
Fixed also.

**Comment by Zunrin** [comment]
The quests now work for all classes!

The Tiki Targets are still unkillable however.
